### PR TITLE
Beta.6

### LINKED ISSUE #676: Wallet display customisation
Some dapps want to select certain wallets to be shown in Web3Modal.

Create a wallet config option so that dapps can choose what wallets are shown.

### LINKED ISSUE #684: Documentation content completion
- [x] Full hooks documentation with correct content / snippets
- [ ] Vanilla usage documentation
- [ ] Standalone usage documentation (placeholder: https://docs.walletconnect.com/2.0/web3modal/standalone)
- [ ] Configuration documentation

### LINKED ISSUE #704: "View All" randomly repositions wallets in the list with each render
**Describe the bug**
Looks like there is array immutability issue in "View All" button, it randomly repositions wallets on each render

**SDK Version**
 - beta.4

### PR DESCRIPTION
**Pull request by IljaDaderko**
## Linked Documentation PR
https://github.com/WalletConnect/walletconnect-docs/pull/337

## New config options
Wagmi connectors are no longer managed manually, thus users can configure them if they don't want to use our defaults. WalletConnect connector is required.

1. `projectId` becomes optional, if not provided some functionality will be lost and users will have to provide their own options i.e. explorer, images endpoint and walletconnect rpc (see new config options below for alternatives)
2. `mobileWallets` - array with simple json for linked mobile wallets (id, name, links - deep / universal)
3. `desktopWallets` - array with simple json for linked desktop / web wallets (id, name, links - deep / universal)
4. `walletImages` - Object mapping wagmi connector id's / custom wallet id's to custom images
5. `chainImages` - Object mapping chain id's to custom images
6. `enableNetworkView` - Flag to enable or dissable network selection view when there are more than 1 chains specified in config, defaults to true

## Upcoming config options
1. `explorerAllowList` - Coming in beta.7, will allow to manage explorer records if projectId was provided
2. `explorerDenyList` - Coming in beta.7, will allow to manage explorer records if projectId was provided

## Other changes
1. Dependency updates
2. Enforced eslint `curly` rule (had a nasty bug with prettier formatting and single line if)
3. Reorganised utilities
4. Added injected connector to mobile when `window.ethereum` is present (i.e. within in wallet browsers like metamask)
5. Added option ctrl flags for each modal mode (standalone, custom mobile, custom desktop, explorer enabled)
6. Added `custom` page to react example to test all of this and showcase usage

closes #676 
closes #704
closes #684

### CODE REVIEW

File: packages/core/src/controllers/ConfigCtrl.ts [hunk 1]
```diff
@@ -23,14 +27,13 @@ export const ConfigCtrl = {
...
-    if (!config.projectId)
-      throw new Error(
-        'Web3Modal requires projectId that can be obtained at cloud.walletconnect.com'
-      )
+  setConfig(config: ConfigCtrlState) {
+    OptionsCtrl.setStandaloneChains(config.standaloneChains)
+    OptionsCtrl.setIsStandalone(Boolean(config.standaloneChains?.length))
+    OptionsCtrl.setIsCustomMobile(Boolean(config.mobileWallets?.length))
+    OptionsCtrl.setIsCustomDesktop(Boolean(config.desktopWallets?.length))
+    OptionsCtrl.setIsExplorer(Boolean(config.projectId?.length))
```
Comment (crypblizz8) [inline packages/core/src/controllers/ConfigCtrl.ts:35]: Minor: TS Pickup: Unnecessary optional chain of a non nullish value. `config.projectId` resolves

Comment (IljaDaderko) [reply packages/core/src/controllers/ConfigCtrl.ts:35]: `projectId` became optional, so can be undefined here. Did you see this error in your editor? Maybe run `yarn` to update everything so that new types are picked up.

File: packages/ui/src/views/w3m-wallet-filter-view/index.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+      : wallets
+
+    return html`
+      ${dynamicStyles()}
+
+      <w3m-modal-header>
+        <w3m-search-input .onChange=${this.onSearchChange.bind(this)}></w3m-search-input>
+      </w3m-modal-header>
+
+      <w3m-modal-content>
```
Comment (crypblizz8) [inline packages/ui/src/views/w3m-wallet-filter-view/index.ts:50]: Minor: Curious about the way the CSS / transition works for the `Modal Content.` Is it preset to a certain height because I can imagine a lot of custom wallets not reaching 25+ explorer content.

I.e. the example in `custom.tsx,` the modal jumps height (under the assumption we have 25+?) + provides a lot of empty space. 

image.

Could we adjust with a ternary that if less than ~20 wallets, no modal height change / jump? (Same Height as the previous page of `ConnectWalletView`?

File: packages/core/src/controllers/ConfigCtrl.ts (hunk 1 above)
Comment (crypblizz8) [reply packages/core/src/controllers/ConfigCtrl.ts:35]: My bad, resolved!

File: packages/ui/src/components/w3m-modal-backcard/index.ts [hunk 3]
```diff
@@ -20,7 +20,7 @@ export class W3mModalBackcard extends LitElement {
 
   // -- lifecycle ---------------------------------------------------- //
   public firstUpdated() {
-    setTimeout(() => {
+    this.playTimeout = setTimeout(() => {
```
[the remark this answers is not in the document]
Comment (IljaDaderko) [reply packages/ui/src/components/w3m-modal-backcard/index.ts:23]: Allows some time for other transitions to complete, as this one is a "heavy" webgl render to set up. There is css gradient fallback while this kicks in

File: packages/ui/src/views/w3m-wallet-filter-view/index.ts (hunk 2 above)
Comment (IljaDaderko) [reply packages/ui/src/views/w3m-wallet-filter-view/index.ts:50]: Good catch, there was a need for this in normal explorer view to avoid jumpy content during loading, but since all wallets are known in custom one, height can be dynamic 👍 updated both to feel nicer.

**Review by crypblizz8 — APPROVED** [review]

File: packages/ui/src/components/w3m-search-input/styles.ts [hunk 4]
```diff
@@ -54,7 +56,7 @@ export default css`
 
   w3m-text {
     opacity: 1;
-    transition: 0.15s opacity ease-in-out;
```
Comment (devceline) [inline packages/ui/src/components/w3m-search-input/styles.ts:57]: These speeds should be standardized at some point

**Review by devceline — DISMISSED** [review]
LGTM
